
name: deploy on push
on: [push]

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v2    
      - name: copy file to server
        uses: garygrossgarten/github-action-scp@v0.7.3
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER_NAME}}          
          port: ${{secrets.SSH_PORT}}
          privateKey : ${{secrets.SSH_KEY}}
          local: "./html/*"
          remote: "/var/www/html"